export const FETCH_NOW_PLAYING_MOVIES_REQUEST = "FETCH_UPCOMING_MOVIES_REQUEST";
export const FETCH_NOW_PLAYING_MOVIES_SUCCESS = "FETCH_UPCOMING_MOVIES_SUCCESS";
export const FETCH_NOW_PLAYING_MOVIES_FAILURE = "FETCH_UPCOMING_MOVIES_FAILURE";
